package com.adf.catan;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'alex' at '9/2/16 4:01 PM' with Gradle 2.12
 *
 * @author alex, @date 9/2/16 4:01 PM
 */
public class Catan {
    public Board createRandomBoard() {
        Board board = new Board();
        return board;
    }
}
